// This file is auto-generated by `pnpm --filter @strictons/db gen:types`.
// Do not edit by hand. Regeneration is wired up in commit #17 of Phase 2.
// Until then, this is a placeholder so the package's exports resolve.

export type Database = Record<string, never>;
